### ISSUE TITLE
本机没有可用ipv4地址

### ISSUE THREAD

**Issue by RockNHawk** [zhupingqi/RuiJi.Net#4]
macOS 下默认设置运行 dotnet  "RuiJi.Net.Cmd.dll"

发生如下错误：

Unhandled Exception: System.Exception: 本机没有可用ipv4地址
   at RuiJi.Net.Core.Utils.IPHelper.GetDefaultIPAddress() in D:\RuiJi.Net\RuiJi.Net.Core\Utils\IPHelper.cs:line 15
   at RuiJi.Net.Core.Utils.IPHelper.FixLocalUrl(String baseUrl) in D:\RuiJi.Net\RuiJi.Net.Core\Utils\IPHelper.cs:line 48
   at RuiJi.Net.Owin.DocumentServer..ctor(String baseUrl) in D:\RuiJi.Net\RuiJi.Net.Owin\DocumentServer.cs:line 23
   at RuiJi.Net.Owin.ServerManager.StartServers() in D:\RuiJi.Net\RuiJi.Net.Owin\ServerManager.cs:line 58
   at RuiJi.Net.Cmd.Program.Main(String[] args) in D:\RuiJi.Net\RuiJi.Net.Cmd\Program.cs:line 18

**Comment by RockNHawk** [comment]
是因为只返回了 127.0.0.1 和一个 ipv6 地址，192.168. 这个地址不知为何没有返回（可能是网络环境的原因，与 Windows 在不同的网络环境中）。

`var ips = Dns.GetHostEntry(Dns.GetHostName()).AddressList.ToList();`
`GetHostIPAddress 又把 127.0.0.1 移除掉了。`

通过这个方法可以获取到 192.168. 这个 IP 地址。

`
foreach (NetworkInterface netInterface in NetworkInterface.GetAllNetworkInterfaces())
{
                Console.WriteLine("Name: " + netInterface.Name);
                Console.WriteLine("Description: " + netInterface.Description);
                Console.WriteLine("Addresses: ");
                IPInterfaceProperties ipProps = netInterface.GetIPProperties();
                foreach (UnicastIPAddressInformation addr in ipProps.UnicastAddresses)
                {
                    Console.WriteLine(" " + addr.Address.ToString());
                }
                Console.WriteLine("");
}
`

**Comment by RockNHawk** [comment]
另外博客可否开放评论？这样也可以就具体文章交流一下。

**Comment by zhupingqi** [comment]
1. 发送到127.0.0.1的数据或者从127.0.0.1返回的数据只会在本机进行传输, 而不进行外部网络传输，所以去掉了
2. macOS 我没法测试。。。 
3. 博客垃圾评论好多 wordpress有好多自己发广告的的软件。。。 还是在github或545931923qq上交流群吧
4. 非常感谢你的建议
